/** Typed API paths for the life-coaching service. */
export const COACHING_ROUTES = {
  CAPACITY: "/api/coaching/capacity",
  LEADS: "/api/coaching/leads",
  ME: "/api/coaching/me",
  CHECKOUT: "/api/coaching/checkout",
  CANCEL_RENEWAL: "/api/coaching/renewal/cancel",
  BILLING_PORTAL: "/api/coaching/billing/payment-method",
  LINK_APP: "/api/coaching/app-link",
  IDENTITY_EXCHANGE: "/api/coaching/identity/exchange",
  IDENTITY_LINK: "/api/coaching/identity/link",
  APPOINTMENTS: "/api/coaching/appointments",
  CHECK_INS: "/api/coaching/check-ins",
  MESSAGES: "/api/coaching/messages",
  ADMIN: {
    OVERVIEW: "/api/admin/coaching/overview",
    CLIENTS: "/api/admin/coaching/clients",
    LEADS: "/api/admin/coaching/leads",
    lead: (leadId: string) => `/api/admin/coaching/leads/${leadId}` as const,
    client: (memberId: string) => `/api/admin/coaching/clients/${memberId}` as const,
    clientCoach: (memberId: string) => `/api/admin/coaching/clients/${memberId}/coach` as const,
    clientPortal: (memberId: string) => `/api/admin/coaching/clients/${memberId}/portal` as const,
    clientCheckInReply: (memberId: string, checkInId: string) => `/api/admin/coaching/clients/${memberId}/check-ins/${checkInId}/reply` as const,
    clientMessages: (memberId: string) => `/api/admin/coaching/clients/${memberId}/messages` as const,
    clientFunction: (memberId: string) => `/api/admin/coaching/clients/${memberId}/function` as const,
    clientAssignmentRetry: (memberId: string, assignmentId: string) => `/api/admin/coaching/clients/${memberId}/assignments/${assignmentId}/retry` as const,
    AVAILABILITY: "/api/admin/coaching/availability",
    APPOINTMENTS: "/api/admin/coaching/appointments",
    APPOINTMENT_CONSULTATION: "/api/admin/coaching/appointments/consultation",
    APPOINTMENT_MEMBER: "/api/admin/coaching/appointments/member",
    appointment: (appointmentId: string) => `/api/admin/coaching/appointments/${appointmentId}` as const,
    appointmentCancel: (appointmentId: string) => `/api/admin/coaching/appointments/${appointmentId}/cancel` as const,
    appointmentOutcome: (appointmentId: string) => `/api/admin/coaching/appointments/${appointmentId}/outcome` as const,
    TIME_OFF: "/api/admin/coaching/time-off",
    SCHEDULING_CONFIGURATION: "/api/admin/coaching/scheduling-configuration",
    BILLING: "/api/admin/coaching/billing",
    ASSIGNMENTS: "/api/admin/coaching/assignments",
    RECONCILE: "/api/admin/coaching/reconcile",
    INVITES: "/api/admin/coaching/invites",
    WORKOUTS_EXERCISES: "/api/admin/coaching/workouts-exercises",
    AI_PLAN_PREVIEW: "/api/admin/coaching/ai-plan-preview",
  },
  WORKOUTS: {
    APP_ACCESS: "/v1/coaching/app-access",
  },
} as const;
